package install

import (
	"fmt"
	"os"
	"path/filepath"
)

type OpenSpecGenerator struct {
	targetDir string
}

func NewOpenSpecGenerator(targetDir string) *OpenSpecGenerator {
	return &OpenSpecGenerator{targetDir: targetDir}
}

// GenerateStructure creates the OpenSpec folder structure
func (g *OpenSpecGenerator) GenerateStructure() error {
	specsDir := filepath.Join(g.targetDir, "openspec", "specs")
	changesDir := filepath.Join(g.targetDir, "openspec", "changes")

	if err := os.MkdirAll(specsDir, 0755); err != nil {
		return fmt.Errorf("failed to create specs dir: %w", err)
	}
	if err := os.MkdirAll(changesDir, 0755); err != nil {
		return fmt.Errorf("failed to create changes dir: %w", err)
	}

	specContent := "# NOUS Project Specification\n\n## Overview\nThis project uses Spec-Driven Development (SDD) workflow managed by NOUS.\n\n## Directory Structure\n- specs/ — Project specifications (create before implementing)\n- changes/ — Change proposals and implementations\n\n## SDD Workflow\n1. SPEC-First: Create/update SPEC.md in openspec/specs/ before any code\n2. Propose: Create CHG_XXX_proposal.md in openspec/changes/\n3. Implement and Verify: Code must match the spec\n\n## Memory System\n- Persistent memory: .agent/MEMORY.md (AAAK encoded)\n- Document index: .agent/docs_index.md\n- Formal ADRs: docs/ (tracked)\n- Technical refs: dev/docs/ (logs, migrations, team context)\n\nGenerated by NOUS.\n"

	if err := os.WriteFile(filepath.Join(specsDir, "SPEC.md"), []byte(specContent), 0644); err != nil {
		return err
	}

	changesReadme := "# OpenSpec Changes\n\nThis directory contains change proposals and implementations.\n\n## Naming Convention\n- CHG_001_description.md - Change proposal\n- CHG_001_implementation.md - Implementation details\n\n## Workflow\n1. Propose: Create CHG_XXX_proposal.md\n2. Review: Team reviews and approves\n3. Implement: Create CHG_XXX_implementation.md\n4. Merge: Apply and update SPEC.md\n\nGenerated by NOUS.\n"

	if err := os.WriteFile(filepath.Join(changesDir, "README.md"), []byte(changesReadme), 0644); err != nil {
		return err
	}

	return nil
}

// CreateProposal creates a new change proposal
func (g *OpenSpecGenerator) CreateProposal(number, title, description string) error {
	changesDir := filepath.Join(g.targetDir, "openspec", "changes")

	proposal := fmt.Sprintf("# Change Proposal: %s\n\n## Number\nCHG_%s\n\n## Title\n%s\n\n## Description\n%s\n\n## Status\nProposed\n\n## Impact\n- Files affected:\n- Breaking changes:\n\n## Implementation Plan\n1.\n2.\n3.\n\n---\nGenerated by NOUS\n", title, number, title, description)

	filename := fmt.Sprintf("CHG_%s_proposal.md", number)
	return os.WriteFile(filepath.Join(changesDir, filename), []byte(proposal), 0644)
}
