package memory

import (
	"fmt"
)

// WakeUp generates the L0 + L1 context (~600-900 tokens) for AI agents
type WakeUpGenerator struct {
	wrapper *MemPalaceWrapper
}

func NewWakeUpGenerator(wrapper *MemPalaceWrapper) *WakeUpGenerator {
	return &WakeUpGenerator{wrapper: wrapper}
}

// Generate creates the wake-up prompt with critical facts
func (g *WakeUpGenerator) Generate(wing string) (string, error) {
	if g.wrapper == nil {
		return g.defaultWakeUp(), nil
	}

	context, err := g.wrapper.WakeUp(wing)
	if err != nil {
		return g.defaultWakeUp(), nil
	}

	return g.formatWakeUp(context), nil
}

func (g *WakeUpGenerator) formatWakeUp(context string) string {
	return fmt.Sprintf(`# NOUS Wake-Up Context

## L0: Identity
You are NOUS, an AI ecosystem configurator. You have persistent memory via MemPalace.

## L1: Critical Facts
%s

## Memory Protocol
- Use MemPalace semantic search for past decisions
- Store new decisions with mempalace_add_drawer
- Follow Wings/Rooms structure for organization

## SDD Workflow
- Spec first: always create/update specs in openspec/specs/
- Changes go in openspec/changes/
- Verify before implementing

Generated by NOUS.`, context)
}

func (g *WakeUpGenerator) defaultWakeUp() string {
	return `# NOUS Wake-Up Context

## L0: Identity
You are NOUS, an AI ecosystem configurator with persistent memory.

## L1: Critical Facts
- Projects are organized in Wings (person/project)
- Rooms contain topics within wings
- Closets are summaries; Drawers are verbatim originals
- Always use semantic search before assuming

## Memory Protocol
- mempalace_search: find past decisions
- mempalace_add_drawer: store verbatim content
- Wings/Rooms structure over flat search

## SDD Workflow
- Spec first: openspec/specs/
- Changes: openspec/changes/
- Verify before implement

NOUS is configured and ready.
`
}